apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "tw-mediawiki.name" . }}-db
    type: {{ .Values.mariadb.type }}
spec:
  selector:
    app: {{ include "tw-mediawiki.name" . }}-db
    type: {{ .Values.mariadb.type }}
  ports:
  - port: {{ .Values.mariadb.port }}
    targetPort: {{ .Values.mariadb.port }}
    nodePort: {{ .Values.mariadb.nodePort }}
  type: {{ .Values.mariadb.serviceType }}
