  
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: physical-volume
  namespace: {{ .Values.namespace.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.name }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi