apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadbSecret.name }}
  namespace: {{ .Values.namespace.name }}
data:
  dbname: {{ .Values.mariadbSecret.dbname }}
  dbpassword: {{ .Values.mariadbSecret.dbpassword }}
  dbrootpassword: {{ .Values.mariadbSecret.dbrootpassword }}
  dbuser: {{ .Values.mariadbSecret.dbuser }}
